export const Regions = [
  { name: "Miền Bắc", code: "miba" },
  { name: "VIP M.Bắc 75 Giây", code: "vnmbmg" },
  { name: "VIP M.Nam 45 Giây", code: "vnmnmg" },
  { name: "VIP  M.Trung 75 Giây", code: "vnmtmg" },
  { name: " VIP  Miền Bắc 3 Phút", code: "vnmiba3m" },
  { name: "Bạc Liêu", code: "bali" },
  { name: "Vietlott 6\u002F45", code: "platmg1p" },
  { name: "Siêu Tốc 45 Giây", code: "st45g" },
  { name: "Siêu Tốc 1 Phút", code: "st1p" },
  { name: "Siêu Tốc 1.5 Phút", code: "st90p" },
  { name: "Siêu Tốc 2 Phút", code: "st2p" },
  { name: "Siêu Tốc 5 Phút", code: "st5p" },
  { name: "VIP Siêu Tốc 45 Giây", code: "vnst45g" },
  { name: " VIP Siêu Tốc 1 Phút", code: "vnst1p" },
  { name: "VIP Siêu Tốc 1.5 Phút", code: "vnst90g" },
  { name: "VIP Siêu Tốc 2 Phút", code: "vnst2p" },
  { name: "VIP Siêu Tốc 5 Phút", code: "vnst5p" },
  { name: "An Giang", code: "angi" },
  { name: "Bình Dương", code: "bidu" },
  { name: "Bình Phước", code: "biph" },
  { name: "Bình Thuận", code: "bith" },
  { name: "Cà Mau", code: "cama" },
  { name: "Cần Thơ", code: "cath" },
  { name: "Đà Lạt", code: "dalat" },
  { name: "Đồng Nai", code: "dona" },
  { name: "Đồng Tháp", code: "doth" },
  { name: "Hậu Giang", code: "hagi" },
  { name: "Kiên Giang", code: "kigi" },
  { name: "Long An", code: "loan" },
  { name: "Sóc Trăng", code: "sotr" },
  { name: "Tây Ninh", code: "tani" },
  { name: "Tiền Giang", code: "tigi" },
  { name: "TP. HCM", code: "tphc" },
  { name: "Trà Vinh", code: "trvi" },
  { name: "Vĩnh Long", code: "vilo" },
  { name: "Vũng Tàu", code: "vuta" },
  { name: "Đà Nẵng", code: "dana" },
  { name: "Bình Định", code: "bidi" },
  { name: "Đắk Lắk", code: "dalak" },
  { name: "Đắk Nông", code: "dano" },
  { name: "Gia Lai", code: "gila" },
  { name: "Khánh Hòa", code: "khho" },
  { name: "Kon Tum", code: "kotu" },
  { name: "Ninh Thuận", code: "nith" },
  { name: "Phú Yên", code: "phye" },
  { name: "Quảng Bình", code: "qubi" },
  { name: "Quảng Nam", code: "quna" },
  { name: "Quảng Ngãi", code: "qung" },
  { name: "Quảng Trị", code: "qutr" },
  { name: "Thừa T. Huế", code: "thth" },
  { name: "M.Bắc 75 Giây", code: "mbmg" },
  { name: "M.Nam Siêu Tốc 45 Giây", code: "mnmg" },
  { name: "M.Trung 75 Giây", code: "mtmg" },
  { name: "Hà Nội VIP", code: "hnvip" },
  { name: "Hồ Chí Minh VIP", code: "hcmvip" },
];
